### ISSUE TITLE
JEI not listed as a dependency 

### ISSUE THREAD

**Issue by Ryhon0** [LIUKRAST/EmiCreateSchematics#2]
On both the Modrinth and CurseForge, JEI isn't listed as a dependency, causing Forge fail to load because the dependency is not met
Tested with EMI 1.1.4 and Create Schematics 1.0 for 1.20.1 and Forge 47.2.17. Installing JEI fixes this issue

**Comment by LIUKRAST** [comment]
Thank you for the report! I did put Jei as dependency even though it's not required. I'll check that as soon as I'm back home

**Comment by YipNZ** [comment]
It seems that JEI is not optional and is definitely required to run:

https://mclo.gs/3mblSaK#L364

<html><body>

[27Apr2024 10:17:04.903] [main/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase
--
 

<span class="level level-critical multiline">§7Currently, §6jei§r§7 is §o§nnot installed</span>
</body>
</html>

**Comment by LIUKRAST** [comment]
Just read the comment I posted just right above ._.

**Comment by YipNZ** [comment]
@LIUKRAST 

Thank you. I did read the previous comment and I was just adding more information about the issue in the form of server log.
