### ISSUE TITLE
EMI not listed as dependency in curse forge

### ISSUE THREAD

**Issue by UdoMorgenstern** [LIUKRAST/EmiCreateSchematics#3]
guess no al lot more info required

used EMI Create Schematics [1.0.0 Forge 1.20.1]
 - dependency missing startup
 
works fine when emi-1.1.6+1.20.1+forge is installed by hand (or curse forge)

**Comment by LIUKRAST** [comment]
Thank you, added the dependency on curseforge and will add it for future updates!
